# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.automation_api import AutomationApi


class TestAutomationApi(unittest.TestCase):
    """AutomationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AutomationApi()

    def tearDown(self) -> None:
        pass

    def test_create_auto_backup(self) -> None:
        """Test case for create_auto_backup

        Create automated backup
        """
        pass

    def test_delete_auto_backup(self) -> None:
        """Test case for delete_auto_backup

        Delete automated backup
        """
        pass

    def test_get_auto_backup(self) -> None:
        """Test case for get_auto_backup

        Get automated backup by ID
        """
        pass

    def test_get_auto_backup_history_details(self) -> None:
        """Test case for get_auto_backup_history_details

        Get workflow execution event history details
        """
        pass

    def test_list_auto_backup(self) -> None:
        """Test case for list_auto_backup

        List all automated backups
        """
        pass

    def test_list_auto_backup_executions(self) -> None:
        """Test case for list_auto_backup_executions

        List automated backup workflow executions
        """
        pass

    def test_update_auto_backup(self) -> None:
        """Test case for update_auto_backup

        Update automated backup
        """
        pass


if __name__ == '__main__':
    unittest.main()
