# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.workflow_execution_list_response import WorkflowExecutionListResponse

class TestWorkflowExecutionListResponse(unittest.TestCase):
    """WorkflowExecutionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowExecutionListResponse:
        """Test WorkflowExecutionListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowExecutionListResponse`
        """
        model = WorkflowExecutionListResponse()
        if include_optional:
            return WorkflowExecutionListResponse(
                executions = [
                    saved.models.list_auto_backup_executions_200_response_executions_inner.listAutoBackupExecutions_200_response_executions_inner(
                        workflow_id = '', 
                        run_id = '', 
                        status = '', 
                        start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        close_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        execution_time = 56, )
                    ]
            )
        else:
            return WorkflowExecutionListResponse(
        )
        """

    def testWorkflowExecutionListResponse(self):
        """Test WorkflowExecutionListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
