# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_create_agent(self) -> None:
        """Test case for create_agent

        Create agent
        """
        pass

    def test_delete_agent(self) -> None:
        """Test case for delete_agent

        Delete agent
        """
        pass

    def test_get_agent(self) -> None:
        """Test case for get_agent

        Get agent by ID
        """
        pass

    def test_list_agents(self) -> None:
        """Test case for list_agents

        List agents
        """
        pass

    def test_update_agent(self) -> None:
        """Test case for update_agent

        Update agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
