# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.auto_backup_list_response import AutoBackupListResponse

class TestAutoBackupListResponse(unittest.TestCase):
    """AutoBackupListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoBackupListResponse:
        """Test AutoBackupListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoBackupListResponse`
        """
        model = AutoBackupListResponse()
        if include_optional:
            return AutoBackupListResponse(
                page = 56,
                limit = 56,
                total = 56,
                items = [
                    saved.models.list_auto_backup_200_response_all_of_items_inner.listAutoBackup_200_response_allOf_items_inner(
                        id = '', 
                        vault_id = '', 
                        workspace_id = '', 
                        type = 'worker', 
                        provider = 'http', 
                        agent_id = '', 
                        zone = '', 
                        schedule = '', 
                        temporal_schedule_id = '', )
                    ]
            )
        else:
            return AutoBackupListResponse(
        )
        """

    def testAutoBackupListResponse(self):
        """Test AutoBackupListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
