# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.backup_list_response import BackupListResponse

class TestBackupListResponse(unittest.TestCase):
    """BackupListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BackupListResponse:
        """Test BackupListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BackupListResponse`
        """
        model = BackupListResponse()
        if include_optional:
            return BackupListResponse(
                page = 56,
                limit = 56,
                total = 56,
                items = [
                    saved.models.list_backups_200_response_all_of_items_inner.listBackups_200_response_allOf_items_inner(
                        id = '', 
                        workspace_id = '', 
                        vault_id = '', 
                        name = '', 
                        description = '', 
                        tags = [
                            ''
                            ], 
                        checksum = '', 
                        size = 56, 
                        content_type = '', 
                        status = 'pending', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        confirmed = True, 
                        verified = True, 
                        presigned_url = '', 
                        presigned_url_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        workflow_id = '', )
                    ]
            )
        else:
            return BackupListResponse(
        )
        """

    def testBackupListResponse(self):
        """Test BackupListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
