# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.backup_job_provider import BackupJobProvider

class TestBackupJobProvider(unittest.TestCase):
    """BackupJobProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBackupJobProvider(self):
        """Test BackupJobProvider"""
        # inst = BackupJobProvider()

if __name__ == '__main__':
    unittest.main()
