# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_signals200_response_all_of_items_inner import ListSignals200ResponseAllOfItemsInner

class TestListSignals200ResponseAllOfItemsInner(unittest.TestCase):
    """ListSignals200ResponseAllOfItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSignals200ResponseAllOfItemsInner:
        """Test ListSignals200ResponseAllOfItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSignals200ResponseAllOfItemsInner`
        """
        model = ListSignals200ResponseAllOfItemsInner()
        if include_optional:
            return ListSignals200ResponseAllOfItemsInner(
                id = '',
                workspace_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                provider = 'email'
            )
        else:
            return ListSignals200ResponseAllOfItemsInner(
        )
        """

    def testListSignals200ResponseAllOfItemsInner(self):
        """Test ListSignals200ResponseAllOfItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
