# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.set_project_encryption_key import SetProjectEncryptionKey

class TestSetProjectEncryptionKey(unittest.TestCase):
    """SetProjectEncryptionKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetProjectEncryptionKey:
        """Test SetProjectEncryptionKey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetProjectEncryptionKey`
        """
        model = SetProjectEncryptionKey()
        if include_optional:
            return SetProjectEncryptionKey(
                client_encryption_key_id = ''
            )
        else:
            return SetProjectEncryptionKey(
                client_encryption_key_id = '',
        )
        """

    def testSetProjectEncryptionKey(self):
        """Test SetProjectEncryptionKey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
