# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.storages_api import StoragesApi


class TestStoragesApi(unittest.TestCase):
    """StoragesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StoragesApi()

    def tearDown(self) -> None:
        pass

    def test_create_storage(self) -> None:
        """Test case for create_storage

        Create storage
        """
        pass

    def test_delete_storage(self) -> None:
        """Test case for delete_storage

        Delete storage
        """
        pass

    def test_get_storage(self) -> None:
        """Test case for get_storage

        Get storage by ID
        """
        pass

    def test_list_storages(self) -> None:
        """Test case for list_storages

        List storages
        """
        pass

    def test_update_storage(self) -> None:
        """Test case for update_storage

        Update storage
        """
        pass


if __name__ == '__main__':
    unittest.main()
