# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.project_list_response import ProjectListResponse

class TestProjectListResponse(unittest.TestCase):
    """ProjectListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectListResponse:
        """Test ProjectListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectListResponse`
        """
        model = ProjectListResponse()
        if include_optional:
            return ProjectListResponse(
                page = 56,
                limit = 56,
                total = 56,
                items = [
                    saved.models.list_projects_200_response_all_of_items_inner.listProjects_200_response_allOf_items_inner(
                        id = '', 
                        name = '', 
                        workspace_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        retention_lock_period = 56, 
                        max_backup_count = 56, 
                        max_backup_age = 56, 
                        compression_level = 56, )
                    ]
            )
        else:
            return ProjectListResponse(
        )
        """

    def testProjectListResponse(self):
        """Test ProjectListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
