# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_auto_backup_executions200_response_executions_inner import ListAutoBackupExecutions200ResponseExecutionsInner

class TestListAutoBackupExecutions200ResponseExecutionsInner(unittest.TestCase):
    """ListAutoBackupExecutions200ResponseExecutionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAutoBackupExecutions200ResponseExecutionsInner:
        """Test ListAutoBackupExecutions200ResponseExecutionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAutoBackupExecutions200ResponseExecutionsInner`
        """
        model = ListAutoBackupExecutions200ResponseExecutionsInner()
        if include_optional:
            return ListAutoBackupExecutions200ResponseExecutionsInner(
                workflow_id = '',
                run_id = '',
                status = '',
                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                close_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                execution_time = 56
            )
        else:
            return ListAutoBackupExecutions200ResponseExecutionsInner(
        )
        """

    def testListAutoBackupExecutions200ResponseExecutionsInner(self):
        """Test ListAutoBackupExecutions200ResponseExecutionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
