# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.signals_api import SignalsApi


class TestSignalsApi(unittest.TestCase):
    """SignalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SignalsApi()

    def tearDown(self) -> None:
        pass

    def test_create_signal(self) -> None:
        """Test case for create_signal

        Create signal
        """
        pass

    def test_delete_signal(self) -> None:
        """Test case for delete_signal

        Delete signal
        """
        pass

    def test_get_signal(self) -> None:
        """Test case for get_signal

        Get signal by ID
        """
        pass

    def test_list_signals(self) -> None:
        """Test case for list_signals

        List signals
        """
        pass

    def test_update_signal(self) -> None:
        """Test case for update_signal

        Update signal
        """
        pass


if __name__ == '__main__':
    unittest.main()
