# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.create_auto_backup_request import CreateAutoBackupRequest

class TestCreateAutoBackupRequest(unittest.TestCase):
    """CreateAutoBackupRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAutoBackupRequest:
        """Test CreateAutoBackupRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAutoBackupRequest`
        """
        model = CreateAutoBackupRequest()
        if include_optional:
            return CreateAutoBackupRequest(
                type = 'worker',
                provider = 'http',
                config = None,
                agent_id = '',
                zone = '',
                schedule = ''
            )
        else:
            return CreateAutoBackupRequest(
                type = 'worker',
                provider = 'http',
                schedule = '',
        )
        """

    def testCreateAutoBackupRequest(self):
        """Test CreateAutoBackupRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
