# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.get_auto_backup_history_details200_response import GetAutoBackupHistoryDetails200Response

class TestGetAutoBackupHistoryDetails200Response(unittest.TestCase):
    """GetAutoBackupHistoryDetails200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAutoBackupHistoryDetails200Response:
        """Test GetAutoBackupHistoryDetails200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAutoBackupHistoryDetails200Response`
        """
        model = GetAutoBackupHistoryDetails200Response()
        if include_optional:
            return GetAutoBackupHistoryDetails200Response(
                events = [
                    saved.models.get_auto_backup_history_details_200_response_events_inner.getAutoBackupHistoryDetails_200_response_events_inner(
                        event_id = 56, 
                        event_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        event_type = '', 
                        details = { }, )
                    ]
            )
        else:
            return GetAutoBackupHistoryDetails200Response(
        )
        """

    def testGetAutoBackupHistoryDetails200Response(self):
        """Test GetAutoBackupHistoryDetails200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
