# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_agents200_response_all_of_items_inner import ListAgents200ResponseAllOfItemsInner

class TestListAgents200ResponseAllOfItemsInner(unittest.TestCase):
    """ListAgents200ResponseAllOfItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAgents200ResponseAllOfItemsInner:
        """Test ListAgents200ResponseAllOfItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAgents200ResponseAllOfItemsInner`
        """
        model = ListAgents200ResponseAllOfItemsInner()
        if include_optional:
            return ListAgents200ResponseAllOfItemsInner(
                id = '',
                name = '',
                workspace_id = '',
                created_at = '',
                updated_at = '',
                client_id = '',
                client_secret = '',
                scope = '',
                public_url = ''
            )
        else:
            return ListAgents200ResponseAllOfItemsInner(
        )
        """

    def testListAgents200ResponseAllOfItemsInner(self):
        """Test ListAgents200ResponseAllOfItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
