# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_auto_backup_executions200_response import ListAutoBackupExecutions200Response

class TestListAutoBackupExecutions200Response(unittest.TestCase):
    """ListAutoBackupExecutions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAutoBackupExecutions200Response:
        """Test ListAutoBackupExecutions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAutoBackupExecutions200Response`
        """
        model = ListAutoBackupExecutions200Response()
        if include_optional:
            return ListAutoBackupExecutions200Response(
                executions = [
                    saved.models.list_auto_backup_executions_200_response_executions_inner.listAutoBackupExecutions_200_response_executions_inner(
                        workflow_id = '', 
                        run_id = '', 
                        status = '', 
                        start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        close_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        execution_time = 56, )
                    ]
            )
        else:
            return ListAutoBackupExecutions200Response(
        )
        """

    def testListAutoBackupExecutions200Response(self):
        """Test ListAutoBackupExecutions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
