# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_payment_methods200_response_inner_card import ListPaymentMethods200ResponseInnerCard

class TestListPaymentMethods200ResponseInnerCard(unittest.TestCase):
    """ListPaymentMethods200ResponseInnerCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListPaymentMethods200ResponseInnerCard:
        """Test ListPaymentMethods200ResponseInnerCard
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListPaymentMethods200ResponseInnerCard`
        """
        model = ListPaymentMethods200ResponseInnerCard()
        if include_optional:
            return ListPaymentMethods200ResponseInnerCard(
                brand = '',
                last4 = '',
                exp_month = 56,
                exp_year = 56
            )
        else:
            return ListPaymentMethods200ResponseInnerCard(
        )
        """

    def testListPaymentMethods200ResponseInnerCard(self):
        """Test ListPaymentMethods200ResponseInnerCard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
