# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_auto_backup200_response import ListAutoBackup200Response

class TestListAutoBackup200Response(unittest.TestCase):
    """ListAutoBackup200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAutoBackup200Response:
        """Test ListAutoBackup200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAutoBackup200Response`
        """
        model = ListAutoBackup200Response()
        if include_optional:
            return ListAutoBackup200Response(
                page = 56,
                limit = 56,
                total = 56,
                items = [
                    saved.models.list_auto_backup_200_response_all_of_items_inner.listAutoBackup_200_response_allOf_items_inner(
                        id = '', 
                        vault_id = '', 
                        workspace_id = '', 
                        type = 'worker', 
                        provider = 'http', 
                        agent_id = '', 
                        zone = '', 
                        schedule = '', 
                        temporal_schedule_id = '', )
                    ]
            )
        else:
            return ListAutoBackup200Response(
        )
        """

    def testListAutoBackup200Response(self):
        """Test ListAutoBackup200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
