# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.billing_api import BillingApi


class TestBillingApi(unittest.TestCase):
    """BillingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BillingApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_subscription(self) -> None:
        """Test case for cancel_subscription

        Cancel subscription
        """
        pass

    def test_create_portal_session(self) -> None:
        """Test case for create_portal_session

        Create Stripe customer portal session
        """
        pass

    def test_create_setup_intent(self) -> None:
        """Test case for create_setup_intent

        Create setup intent for payment method
        """
        pass

    def test_get_current_usage(self) -> None:
        """Test case for get_current_usage

        Get current billing period usage
        """
        pass

    def test_get_subscription(self) -> None:
        """Test case for get_subscription

        Get subscription information
        """
        pass

    def test_list_invoices(self) -> None:
        """Test case for list_invoices

        List invoices
        """
        pass

    def test_list_payment_methods(self) -> None:
        """Test case for list_payment_methods

        List payment methods
        """
        pass

    def test_remove_payment_method(self) -> None:
        """Test case for remove_payment_method

        Remove payment method
        """
        pass

    def test_set_default_payment_method(self) -> None:
        """Test case for set_default_payment_method

        Set default payment method
        """
        pass


if __name__ == '__main__':
    unittest.main()
