# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.keys_api import KeysApi


class TestKeysApi(unittest.TestCase):
    """KeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_key(self) -> None:
        """Test case for create_key

        Create encryption key
        """
        pass

    def test_delete_key(self) -> None:
        """Test case for delete_key

        Delete encryption key
        """
        pass

    def test_get_key(self) -> None:
        """Test case for get_key

        Get encryption key by ID
        """
        pass

    def test_list_keys(self) -> None:
        """Test case for list_keys

        List encryption keys
        """
        pass

    def test_update_key(self) -> None:
        """Test case for update_key

        Update encryption key
        """
        pass


if __name__ == '__main__':
    unittest.main()
