# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_keys200_response_all_of_items_inner import ListKeys200ResponseAllOfItemsInner

class TestListKeys200ResponseAllOfItemsInner(unittest.TestCase):
    """ListKeys200ResponseAllOfItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListKeys200ResponseAllOfItemsInner:
        """Test ListKeys200ResponseAllOfItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListKeys200ResponseAllOfItemsInner`
        """
        model = ListKeys200ResponseAllOfItemsInner()
        if include_optional:
            return ListKeys200ResponseAllOfItemsInner(
                id = '',
                name = '',
                workspace_id = '',
                finger_print = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ListKeys200ResponseAllOfItemsInner(
        )
        """

    def testListKeys200ResponseAllOfItemsInner(self):
        """Test ListKeys200ResponseAllOfItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
