# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_workspaces200_response import ListWorkspaces200Response

class TestListWorkspaces200Response(unittest.TestCase):
    """ListWorkspaces200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkspaces200Response:
        """Test ListWorkspaces200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkspaces200Response`
        """
        model = ListWorkspaces200Response()
        if include_optional:
            return ListWorkspaces200Response(
                page = 56,
                limit = 56,
                total = 56,
                items = [
                    saved.models.list_workspaces_200_response_all_of_items_inner.listWorkspaces_200_response_allOf_items_inner(
                        id = '', 
                        name = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ListWorkspaces200Response(
        )
        """

    def testListWorkspaces200Response(self):
        """Test ListWorkspaces200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
