# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_auto_backup200_response_all_of_items_inner import ListAutoBackup200ResponseAllOfItemsInner

class TestListAutoBackup200ResponseAllOfItemsInner(unittest.TestCase):
    """ListAutoBackup200ResponseAllOfItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAutoBackup200ResponseAllOfItemsInner:
        """Test ListAutoBackup200ResponseAllOfItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAutoBackup200ResponseAllOfItemsInner`
        """
        model = ListAutoBackup200ResponseAllOfItemsInner()
        if include_optional:
            return ListAutoBackup200ResponseAllOfItemsInner(
                id = '',
                vault_id = '',
                workspace_id = '',
                type = 'worker',
                provider = 'http',
                agent_id = '',
                zone = '',
                schedule = '',
                temporal_schedule_id = ''
            )
        else:
            return ListAutoBackup200ResponseAllOfItemsInner(
        )
        """

    def testListAutoBackup200ResponseAllOfItemsInner(self):
        """Test ListAutoBackup200ResponseAllOfItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
