# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create workspace
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        Delete workspace
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Get workspace by ID
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        List workspaces
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Update workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
