# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.backups_api import BackupsApi


class TestBackupsApi(unittest.TestCase):
    """BackupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BackupsApi()

    def tearDown(self) -> None:
        pass

    def test_confirm_backup_uploaded(self) -> None:
        """Test case for confirm_backup_uploaded

        Confirm backup uploaded
        """
        pass

    def test_create_backup(self) -> None:
        """Test case for create_backup

        Create backup (request upload)
        """
        pass

    def test_get_backup(self) -> None:
        """Test case for get_backup

        Get backup by ID
        """
        pass

    def test_list_backups(self) -> None:
        """Test case for list_backups

        List backups
        """
        pass

    def test_request_backup_copy(self) -> None:
        """Test case for request_backup_copy

        Request backup copy for download
        """
        pass


if __name__ == '__main__':
    unittest.main()
