# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.create_auto_backup_json import CreateAutoBackupJson

class TestCreateAutoBackupJson(unittest.TestCase):
    """CreateAutoBackupJson unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAutoBackupJson:
        """Test CreateAutoBackupJson
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAutoBackupJson`
        """
        model = CreateAutoBackupJson()
        if include_optional:
            return CreateAutoBackupJson(
                type = 'worker',
                provider = 'http',
                config = None,
                agent_id = '',
                zone = '',
                schedule = ''
            )
        else:
            return CreateAutoBackupJson(
                type = 'worker',
                provider = 'http',
                schedule = '',
        )
        """

    def testCreateAutoBackupJson(self):
        """Test CreateAutoBackupJson"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
