# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.get_current_usage200_response import GetCurrentUsage200Response

class TestGetCurrentUsage200Response(unittest.TestCase):
    """GetCurrentUsage200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCurrentUsage200Response:
        """Test GetCurrentUsage200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCurrentUsage200Response`
        """
        model = GetCurrentUsage200Response()
        if include_optional:
            return GetCurrentUsage200Response(
                storage_gb = 1.337,
                computation_seconds = 1.337,
                transfer_gb = 1.337,
                period_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                period_end = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return GetCurrentUsage200Response(
        )
        """

    def testGetCurrentUsage200Response(self):
        """Test GetCurrentUsage200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
