# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.create_portal_session200_response import CreatePortalSession200Response

class TestCreatePortalSession200Response(unittest.TestCase):
    """CreatePortalSession200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePortalSession200Response:
        """Test CreatePortalSession200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePortalSession200Response`
        """
        model = CreatePortalSession200Response()
        if include_optional:
            return CreatePortalSession200Response(
                url = ''
            )
        else:
            return CreatePortalSession200Response(
        )
        """

    def testCreatePortalSession200Response(self):
        """Test CreatePortalSession200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
