# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_add_project_signal(self) -> None:
        """Test case for add_project_signal

        Add signal to vault
        """
        pass

    def test_add_project_storage(self) -> None:
        """Test case for add_project_storage

        Add storage to vault
        """
        pass

    def test_create_project(self) -> None:
        """Test case for create_project

        Create vault
        """
        pass

    def test_delete_project(self) -> None:
        """Test case for delete_project

        Delete vault
        """
        pass

    def test_delete_project_key(self) -> None:
        """Test case for delete_project_key

        Delete vault encryption key
        """
        pass

    def test_delete_project_signal(self) -> None:
        """Test case for delete_project_signal

        Remove signal from vault
        """
        pass

    def test_delete_project_storage(self) -> None:
        """Test case for delete_project_storage

        Remove storage from vault
        """
        pass

    def test_get_project(self) -> None:
        """Test case for get_project

        Get vault by ID
        """
        pass

    def test_get_project_key(self) -> None:
        """Test case for get_project_key

        Get vault encryption key
        """
        pass

    def test_list_project_signals(self) -> None:
        """Test case for list_project_signals

        List vault signals
        """
        pass

    def test_list_project_storages(self) -> None:
        """Test case for list_project_storages

        List vault storages
        """
        pass

    def test_list_projects(self) -> None:
        """Test case for list_projects

        List vaults
        """
        pass

    def test_set_project_key(self) -> None:
        """Test case for set_project_key

        Set vault encryption key
        """
        pass

    def test_update_project(self) -> None:
        """Test case for update_project

        Update vault
        """
        pass


if __name__ == '__main__':
    unittest.main()
