# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.create_setup_intent200_response import CreateSetupIntent200Response

class TestCreateSetupIntent200Response(unittest.TestCase):
    """CreateSetupIntent200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSetupIntent200Response:
        """Test CreateSetupIntent200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSetupIntent200Response`
        """
        model = CreateSetupIntent200Response()
        if include_optional:
            return CreateSetupIntent200Response(
                client_secret = '',
                id = ''
            )
        else:
            return CreateSetupIntent200Response(
        )
        """

    def testCreateSetupIntent200Response(self):
        """Test CreateSetupIntent200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
