# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.list_projects200_response_all_of_items_inner import ListProjects200ResponseAllOfItemsInner

class TestListProjects200ResponseAllOfItemsInner(unittest.TestCase):
    """ListProjects200ResponseAllOfItemsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListProjects200ResponseAllOfItemsInner:
        """Test ListProjects200ResponseAllOfItemsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListProjects200ResponseAllOfItemsInner`
        """
        model = ListProjects200ResponseAllOfItemsInner()
        if include_optional:
            return ListProjects200ResponseAllOfItemsInner(
                id = '',
                name = '',
                workspace_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                retention_lock_period = 56,
                max_backup_count = 56,
                max_backup_age = 56,
                compression_level = 56
            )
        else:
            return ListProjects200ResponseAllOfItemsInner(
        )
        """

    def testListProjects200ResponseAllOfItemsInner(self):
        """Test ListProjects200ResponseAllOfItemsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
