# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from saved.models.create_project import CreateProject

class TestCreateProject(unittest.TestCase):
    """CreateProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProject:
        """Test CreateProject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProject`
        """
        model = CreateProject()
        if include_optional:
            return CreateProject(
                name = '',
                retention_lock_period = 56,
                max_backup_count = 56,
                max_backup_age = 56,
                compression_level = 56
            )
        else:
            return CreateProject(
                name = '',
        )
        """

    def testCreateProject(self):
        """Test CreateProject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
