# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AutoBackupResponse(BaseModel):
    """
    AutoBackupResponse
    """ # noqa: E501
    id: Optional[StrictStr] = None
    vault_id: Optional[StrictStr] = None
    workspace_id: Optional[StrictStr] = None
    type: Optional[StrictStr] = Field(default=None, description="Type of backup execution - 'worker' for cloud-managed, 'agent' for self-hosted")
    provider: Optional[StrictStr] = Field(default=None, description="Backup provider type (currently supports HTTP, extensible for future providers)")
    agent_id: Optional[StrictStr] = Field(default=None, description="Only present when type is 'agent'")
    zone: Optional[StrictStr] = Field(default=None, description="Only present when type is 'worker'")
    schedule: Optional[StrictStr] = Field(default=None, description="Cron expression")
    temporal_schedule_id: Optional[StrictStr] = Field(default=None, description="Temporal workflow schedule ID")
    __properties: ClassVar[List[str]] = ["id", "vault_id", "workspace_id", "type", "provider", "agent_id", "zone", "schedule", "temporal_schedule_id"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['worker', 'agent']):
            raise ValueError("must be one of enum values ('worker', 'agent')")
        return value

    @field_validator('provider')
    def provider_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['http']):
            raise ValueError("must be one of enum values ('http')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AutoBackupResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AutoBackupResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "vault_id": obj.get("vault_id"),
            "workspace_id": obj.get("workspace_id"),
            "type": obj.get("type"),
            "provider": obj.get("provider"),
            "agent_id": obj.get("agent_id"),
            "zone": obj.get("zone"),
            "schedule": obj.get("schedule"),
            "temporal_schedule_id": obj.get("temporal_schedule_id")
        })
        return _obj


