# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BackupJobType(str, Enum):
    """
    Type of backup execution - 'worker' for cloud-managed, 'agent' for self-hosted
    """

    """
    allowed enum values
    """
    WORKER = 'worker'
    AGENT = 'agent'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BackupJobType from a JSON string"""
        return cls(json.loads(json_str))


