# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BackupJobProvider(str, Enum):
    """
    Backup provider type (currently supports HTTP, extensible for future providers)
    """

    """
    allowed enum values
    """
    HTTP = 'http'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BackupJobProvider from a JSON string"""
        return cls(json.loads(json_str))


