# coding: utf-8

"""
    BackedUp API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BackupResponse(BaseModel):
    """
    BackupResponse
    """ # noqa: E501
    id: Optional[StrictStr] = None
    workspace_id: Optional[StrictStr] = None
    vault_id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = Field(default=None, description="List of tags")
    checksum: Optional[StrictStr] = Field(default=None, description="SHA256 hash of the backup file")
    size: Optional[StrictInt] = Field(default=None, description="Size of the backup in bytes")
    content_type: Optional[StrictStr] = Field(default=None, description="MIME type of the file")
    status: Optional[StrictStr] = Field(default=None, description="Current status of the backup")
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    confirmed: Optional[StrictBool] = Field(default=None, description="Whether the backup upload has been confirmed")
    verified: Optional[StrictBool] = Field(default=None, description="Whether the backup has been verified")
    presigned_url: Optional[StrictStr] = Field(default=None, description="S3 presigned URL for backup upload/download")
    presigned_url_expires_at: Optional[datetime] = Field(default=None, description="When the presigned URL expires")
    workflow_id: Optional[StrictStr] = Field(default=None, description="Temporal workflow ID")
    __properties: ClassVar[List[str]] = ["id", "workspace_id", "vault_id", "name", "description", "tags", "checksum", "size", "content_type", "status", "created_at", "updated_at", "confirmed", "verified", "presigned_url", "presigned_url_expires_at", "workflow_id"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'uploading', 'processing', 'completed', 'completed_with_errors', 'failed']):
            raise ValueError("must be one of enum values ('pending', 'uploading', 'processing', 'completed', 'completed_with_errors', 'failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BackupResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BackupResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "workspace_id": obj.get("workspace_id"),
            "vault_id": obj.get("vault_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "tags": obj.get("tags"),
            "checksum": obj.get("checksum"),
            "size": obj.get("size"),
            "content_type": obj.get("content_type"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "confirmed": obj.get("confirmed"),
            "verified": obj.get("verified"),
            "presigned_url": obj.get("presigned_url"),
            "presigned_url_expires_at": obj.get("presigned_url_expires_at"),
            "workflow_id": obj.get("workflow_id")
        })
        return _obj


