# coding: utf-8

"""
    Saved API

    Microservices-based backup and vault management platform with encrypted backups and distributed storage

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ListAgents200ResponseAllOfItemsInner(BaseModel):
    """
    ListAgents200ResponseAllOfItemsInner
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    workspace_id: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    updated_at: Optional[StrictStr] = None
    client_id: Optional[StrictStr] = None
    client_secret: Optional[StrictStr] = None
    scope: Optional[StrictStr] = None
    public_url: Optional[StrictStr] = None
    status: Optional[StrictStr] = Field(default=None, description="Current status of the agent")
    certificate_cn: Optional[StrictStr] = Field(default=None, description="Certificate common name")
    certificate_expiry: Optional[datetime] = Field(default=None, description="Certificate expiration date")
    temporal_namespace: Optional[StrictStr] = Field(default=None, description="Temporal namespace for this agent")
    temporal_task_queue: Optional[StrictStr] = Field(default=None, description="Temporal task queue name")
    temporal_host_port: Optional[StrictStr] = Field(default=None, description="Temporal host and port")
    __properties: ClassVar[List[str]] = ["id", "name", "workspace_id", "created_at", "updated_at", "client_id", "client_secret", "scope", "public_url", "status", "certificate_cn", "certificate_expiry", "temporal_namespace", "temporal_task_queue", "temporal_host_port"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'pending_certificate', 'disabled']):
            raise ValueError("must be one of enum values ('active', 'pending_certificate', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListAgents200ResponseAllOfItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListAgents200ResponseAllOfItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "workspace_id": obj.get("workspace_id"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "client_id": obj.get("client_id"),
            "client_secret": obj.get("client_secret"),
            "scope": obj.get("scope"),
            "public_url": obj.get("public_url"),
            "status": obj.get("status"),
            "certificate_cn": obj.get("certificate_cn"),
            "certificate_expiry": obj.get("certificate_expiry"),
            "temporal_namespace": obj.get("temporal_namespace"),
            "temporal_task_queue": obj.get("temporal_task_queue"),
            "temporal_host_port": obj.get("temporal_host_port")
        })
        return _obj


